const config = require('./config')
const fs = require('fs')
const path = require('path');

require('@nomiclabs/hardhat-waffle')
require("@nomiclabs/hardhat-etherscan");
require("hardhat-gas-reporter");
require('solidity-coverage');
require('hardhat-abi-exporter');

// This is a sample Buidler task. To learn how to create your own go to
// https://buidler.dev/guides/create-task.html
task('accounts', 'Prints the list of accounts', async () => {
    const accounts = await ethers.getSigners()

    for (const account of accounts) {
        console.log(await account.getAddress())
    }
})

task('minify-abi', 'minifies abis generated by the abiExporter plugin', async () => {
    const directory = path.join(__dirname, 'abi')
    fs.readdirSync(directory).forEach(file => {
        const abiFile = path.resolve(directory, file)
        const abiJson = require(abiFile)
        const minified = JSON.stringify(abiJson)
        fs.writeFileSync(abiFile, minified )
    })
})

// Some of the settings should be defined in `./config.js`.
// Go to https://buidler.dev/config/ for the syntax.
module.exports = {
    solidity: {
        version: '0.6.12',
        settings: {
            optimizer: {
                enabled: true,
                runs: 1000,
            },
        },
    },

    defaultNetwork: "hardhat",

    networks: config.networks,
    etherscan: config.etherscan,

    gasReporter: {
        enabled: !!(process.env.REPORT_GAS),
    },

    abiExporter: {
        path: './abi',
        only: ['Staking', 'YieldFarmLP', 'YieldFarmUnix', 'CommunityVault'],
        clear: true,
        flat: true,
    },
}
